services:
  eventflow-api:
    container_name: eventflow-api
    image: alysonsz/eventflow-api:v1.0.0
    ports:
      - "8079:8079"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8079
      - ConnectionStrings__DevConnectionString=Server=eventflow-db;Database=EventFlow;User Id=sa;Password=MyStrongPassword123!;TrustServerCertificate=True;
      - Jwt__Issuer=EventFlowApi
      - Jwt__Audience=EventFlowClient
      - Jwt__Key=UmaChaveMuitoSecretaEMuitoLongaParaDev123!
      - Serilog__WriteTo__1__Args__serverUrl=http://eventflow-seq:5341
      - ASPNETCORE_DataProtection__KeyManagement__XmlRepository__Directory=/root/.aspnet/DataProtection-Keys
    depends_on:
      eventflow-db:
        condition: service_healthy
      eventflow-seq:
        condition: service_started
    volumes:
    - eventflow_keys:/root/.aspnet/DataProtection-Keys
    networks:
      - eventflow-network

  eventflow-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventflow-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123!
    ports:
      - "1434:1434"
    volumes:
      - eventflow_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MyStrongPassword123!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - eventflow-network

  eventflow-seq:
    image: datalust/seq:latest
    container_name: eventflow-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=MyStrongPassword123!
    ports:
      - "5341:80"
    networks:
      - eventflow-network

  eventflow-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: eventflow-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - eventflow-network
      
  eventflow-redis:
    image: redis:alpine
    container_name: eventflow-redis
    ports:
      - "6379:6379"
    networks:
      - eventflow-network

volumes:
  eventflow_sql_data:
  eventflow_keys:

networks:
  eventflow-network:
    driver: bridge